name: CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Generate Deployment Package
        # run: zip -r nodejs-app-build.zip .
        run: zip -r nodejs-app-build.zip . -x "*.git*" "*.github*" "node_modules/*" "tests/*"
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'node-app-demo'
          environment_name: 'Node-app-demo-env'
          version_label: "${{ github.sha }}-${{ github.run_id }}"
          region: ap-south-1
          deployment_package: nodejs-app-build.zip
          use_existing_version_if_available: true

